services:
  backend:
    build: ./backend
    ports:
      - '8081:8080'
    restart: unless-stopped
    mem_limit: 512m
    cpus: 0.5

  frontend:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    restart: unless-stopped 
    mem_limit: 512m
    cpus: 0.5
