version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '8081:8080'
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    restart: unless-stopped 